[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
